### ISSUE TITLE
Python 3.4 woes

### ISSUE THREAD

**Issue by AjaxFB** [monolithworks/trueseeing#108]
analyze: disassembling... Traceback (most recent call last):
  File "/usr/local/bin/trueseeing", line 9, in <module>
    load_entry_point('trueseeing==2.0.9', 'console_scripts', 'trueseeing')()
  File "/usr/local/lib/python3.4/dist-packages/trueseeing-2.0.9-py3.4.egg/trueseeing/shell.py", line 197, in shell
    if processed(f, [v for k,v in signatures.items() if k in signature_selected], output_format=output_format):
  File "/usr/local/lib/python3.4/dist-packages/trueseeing-2.0.9-py3.4.egg/trueseeing/shell.py", line 48, in processed
    context.analyze(apkfilename)
  File "/usr/local/lib/python3.4/dist-packages/trueseeing-2.0.9-py3.4.egg/trueseeing/context.py", line 74, in analyze
    subprocess.run("java -jar %(apktool)s d -f %(skipresflag)s -o %(wd)s %(apk)s" % dict(apktool=pkg_resources.resource_filename(__name__, os.path.join('libs', 'apktool.jar')), wd=self.wd, apk=self.apk, skipresflag=('-r' if skip_resources else '')), shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
AttributeError: 'module' object has no attribute 'run'

**Comment by alterakey** [comment]
Thank you for your report!  It seems like subprocess.run, the function trueseeing is using, is added from Python 3.5.  I think some backporting needed for 3.4.

**Comment by alterakey** [comment]
Fixed in py34-fix branch, merged into master.  While 2.0.10 will fix the issue, you can test the py34-fix branch.  Closing case.
