### ISSUE TITLE
error in  trueseeing/shell.py when testing the apk

### ISSUE THREAD

**Issue by nuc13us** [monolithworks/trueseeing#119]
**trueseeing** Desktop/appentry-general-debug.apk 

Desktop/appentry-general-debug.apk -> /Users/XXXXX/.trueseeing2/6a/60/a725888b50db760b61e8abf1ea728d358a1de37a604fab19f826d096f5a0
analyzing: 66.7%: critical:2 high:9 medium:18 low:1040 info:1903Traceback (most recent call last):
  File "/usr/local/bin/trueseeing", line 10, in <module>
    sys.exit(shell())
  File "/usr/local/lib/python3.7/site-packages/trueseeing/shell.py", line 200, in shell
    if processed(f, [v for k,v in signatures.items() if k in signature_selected], output_format=output_format):
  File "/usr/local/lib/python3.7/site-packages/trueseeing/shell.py", line 64, in processed
    for e in c(context).detect():
  File "/usr/local/lib/python3.7/site-packages/trueseeing/signature/base.py", line 39, in detect
    yield from res
  File "/usr/local/lib/python3.7/site-packages/trueseeing/signature/security.py", line 211, in do_detect
    info1='{0} (score: {1:.02f})'.format(t.attrib['{0}id'.format(self.xmlns_android)], size),
  File "src/lxml/etree.pyx", line 2455, in lxml.etree._Attrib.__getitem__
KeyError: '{http://schemas.android.com/apk/res/android}id'

**Comment by alterakey** [comment]
Hello @nuc13us, thanks for your report. I will take a look at this. I think I can fix it faster if I could get the offending APK, would you mind if you provide me with it?

**Comment by nuc13us** [comment]
Hello @alterakey, I am sorry. I was trying to scan on debug mode apk on one of the confidential apk. I can let you know if you need any other inputs.

**Comment by alterakey** [comment]
I got it, it's OK.

**Comment by alterakey** [comment]
Merged temporary fix; it should not crash at least -- closing the issue for now. If you still run into problem like this please re-open. Thank you for your cooperation.
